### ISSUE TITLE
upgrade to ASU header v5.0

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Wordpress-Theme#79] opened 2015-02-18 18:11 UTC
we are currently at v4.0
https://drupal.asu.edu/build/asu-header-footer-version-43

**Comment by rraub** [comment] 2015-03-05 18:46
On Hold until v5.0, we've pulled in the big visual change to the menu items. 

Related: https://asudev.jira.com/projects/WSHF/issues/WSHF-7?filter=allopenissues and https://asudev.jira.com/projects/WSHF/issues/WSHF-8?filter=allopenissues

**Comment by idmontie** [comment] 2015-07-21 17:29
Still on hold. The header is on hold by UTO.

**Comment by idmontie** [comment] 2016-02-29 17:10
Duplicate of #222 . 4.4 will come out before v5 and will "most likely" fix the problems we were having with the header (which was the responsiveness).

**Closed** 2016-02-29 17:10 UTC
Labels: enhancement, on hold
